# Generated by Django 4.1.4 on 2022-12-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("x_pos", models.FloatField()),
                ("y_pos", models.FloatField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playertracker.player",
                    ),
                ),
            ],
        ),
    ]
