# Generated by Django 4.1.4 on 2022-12-17 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0002_relic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relic",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relics",
                to="playertracker.player",
            ),
        ),
    ]
