# Generated by Django 4.1.4 on 2022-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0003_alter_relic_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relic",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
