# Generated by Django 4.1.4 on 2022-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0004_alter_relic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
