# Generated by Django 4.1.4 on 2022-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0005_alter_relic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="screen_height",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="screen_width",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relic",
            name="height",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relic",
            name="width",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
