# Generated by Django 4.1.4 on 2022-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playertracker", "0006_player_screen_height_player_screen_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="deck_button_height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="deck_button_width",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="deck_button_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="deck_button_y",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="map_button_height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="map_button_width",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="map_button_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="map_button_y",
            field=models.FloatField(default=0),
        ),
    ]
