# Generated by Django 4.1.4 on 2022-12-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playertracker",
            "0007_player_deck_button_height_player_deck_button_width_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_current_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_max_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="screen_height",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="screen_width",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="relic",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="relic",
            name="width",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="relic",
            name="x_pos",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="relic",
            name="y_pos",
            field=models.FloatField(default=0),
        ),
    ]
